"use client";

import React from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { toast } from "sonner"


const managers = [
  {
    id: 1,
    name: "John Smith",
    bio: "Seasoned leader with 15 years of experience in project management.",
    email: "john.smith@company.com",
    contact: "+1-555-0101",
    office: "Office A",
    position: "Senior Manager",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    bio: "Expert in team motivation and operational efficiency.",
    email: "sarah.johnson@company.com",
    contact: "+1-555-0102",
    office: "Office B",
    position: "Team Lead",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
  },
  {
    id: 3,
    name: "Michael Brown",
    bio: "Specializes in strategic planning and resource allocation.",
    email: "michael.brown@company.com",
    contact: "+1-555-0103",
    office: "Office C",
    position: "Senior Manager",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
  },
  {
    id: 4,
    name: "Emily Davis",
    bio: "Passionate about employee development and mentorship.",
    email: "emily.davis@company.com",
    contact: "+1-555-0104",
    office: "Office D",
    position: "Team Lead",
    image: "https://images.unsplash.com/photo-1487412723647-8dcaf443e851",
  },
  {
    id: 5,
    name: "David Wilson",
    bio: "Experienced in cross-functional team leadership.",
    email: "david.wilson@company.com",
    contact: "+1-555-0105",
    office: "Office E",
    position: "Senior Manager",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
  },
  {
    id: 6,
    name: "Lisa Anderson",
    bio: "Skilled in conflict resolution and team building.",
    email: "lisa.anderson@company.com",
    contact: "+1-555-0106",
    office: "Office A",
    position: "Team Lead",
    image: "https://images.unsplash.com/photo-1517841902196-6c0ebfcdd114",
  },
  {
    id: 7,
    name: "Robert Taylor",
    bio: "Expert in process optimization and performance metrics.",
    email: "robert.taylor@company.com",
    contact: "+1-555-0107",
    office: "Office B",
    position: "Senior Manager",
    image: "https://images.unsplash.com/photo-1522529599102-1a6c08f8e4a4",
  },
  {
    id: 8,
    name: "Jennifer Martinez",
    bio: "Focused on innovative management strategies.",
    email: "jennifer.martinez@company.com",
    contact: "+1-555-0108",
    office: "Office C",
    position: "Team Lead",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
  },
  {
    id: 9,
    name: "Thomas Lee",
    bio: "Proven track record in departmental leadership.",
    email: "thomas.lee@company.com",
    contact: "+1-555-0109",
    office: "Office D",
    position: "Senior Manager",
    image: "https://images.unsplash.com/photo-1504257432389-52343af06ae3",
  },
  {
    id: 10,
    name: "Rachel White",
    bio: "Dedicated to fostering a positive work environment.",
    email: "rachel.white@company.com",
    contact: "+1-555-0110",
    office: "Office E",
    position: "Team Lead",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7",
  },
  

    {
      id: 11,
      name: "James Carter",
      bio: "Proven leader in agile project management.",
      email: "james.carter@company.com",
      contact: "+1-555-0111",
      office: "Office A",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    },
    {
      id: 12,
      name: "Kelly Green",
      bio: "Focuses on team dynamics and productivity.",
      email: "kelly.green@company.com",
      contact: "+1-555-0112",
      office: "Office B",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    },
    {
      id: 13,
      name: "Peter Adams",
      bio: "Specializes in budget oversight and planning.",
      email: "peter.adams@company.com",
      contact: "+1-555-0113",
      office: "Office C",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7",
    },
    {
      id: 14,
      name: "Laura Bennett",
      bio: "Dedicated to improving team morale.",
      email: "laura.bennett@company.com",
      contact: "+1-555-0114",
      office: "Office D",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
    {
      id: 15,
      name: "Mark Evans",
      bio: "Experienced in organizational restructuring.",
      email: "mark.evans@company.com",
      contact: "+1-555-0115",
      office: "Office E",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    {
      id: 16,
      name: "Sophie Clark",
      bio: "Skilled in mentoring young professionals.",
      email: "sophie.clark@company.com",
      contact: "+1-555-0116",
      office: "Office A",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1487412723647-8dcaf443e851",
    },
    {
      id: 17,
      name: "Henry Moore",
      bio: "Expert in risk management and mitigation.",
      email: "henry.moore@company.com",
      contact: "+1-555-0117",
      office: "Office B",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    },
    {
      id: 18,
      name: "Olivia Turner",
      bio: "Passionate about diversity and inclusion.",
      email: "olivia.turner@company.com",
      contact: "+1-555-0118",
      office: "Office C",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    },
    {
      id: 19,
      name: "Daniel King",
      bio: "Strong background in operational leadership.",
      email: "daniel.king@company.com",
      contact: "+1-555-0119",
      office: "Office D",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1504257432389-52343af06ae3",
    },
    {
      id: 20,
      name: "Grace Hall",
      bio: "Focuses on employee engagement strategies.",
      email: "grace.hall@company.com",
      contact: "+1-555-0120",
      office: "Office E",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1517841902196-6c0ebfcdd114",
    },
    {
      id: 21,
      name: "Ethan Brooks",
      bio: "Experienced in scaling team operations.",
      email: "ethan.brooks@company.com",
      contact: "+1-555-0121",
      office: "Office A",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    },
    {
      id: 22,
      name: "Chloe Wright",
      bio: "Skilled in performance coaching.",
      email: "chloe.wright@company.com",
      contact: "+1-555-0122",
      office: "Office B",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1522529599102-1a6c08f8e4a4",
    },
    {
      id: 23,
      name: "Liam Scott",
      bio: "Expert in resource optimization.",
      email: "liam.scott@company.com",
      contact: "+1-555-0123",
      office: "Office C",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    },
    {
      id: 24,
      name: "Ava Phillips",
      bio: "Dedicated to process improvement.",
      email: "ava.phillips@company.com",
      contact: "+1-555-0124",
      office: "Office D",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
    {
      id: 25,
      name: "Noah Reed",
      bio: "Specializes in cross-departmental collaboration.",
      email: "noah.reed@company.com",
      contact: "+1-555-0125",
      office: "Office E",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    {
      id: 26,
      name: "Mia Collins",
      bio: "Focuses on innovative team strategies.",
      email: "mia.collins@company.com",
      contact: "+1-555-0126",
      office: "Office A",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1487412723647-8dcaf443e851",
    },
    {
      id: 27,
      name: "Lucas Gray",
      bio: "Experienced in project execution.",
      email: "lucas.gray@company.com",
      contact: "+1-555-0127",
      office: "Office B",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    },
    {
      id: 28,
      name: "Isabella Cook",
      bio: "Skilled in conflict mediation.",
      email: "isabella.cook@company.com",
      contact: "+1-555-0128",
      office: "Office C",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    },
    {
      id: 29,
      name: "Mason Perry",
      bio: "Expert in strategic forecasting.",
      email: "mason.perry@company.com",
      contact: "+1-555-0129",
      office: "Office D",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1504257432389-52343af06ae3",
    },
    {
      id: 30,
      name: "Harper Ross",
      bio: "Passionate about team empowerment.",
      email: "harper.ross@company.com",
      contact: "+1-555-0130",
      office: "Office E",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1517841902196-6c0ebfcdd114",
    },
    {
      id: 31,
      name: "Logan Ward",
      bio: "Strong focus on operational excellence.",
      email: "logan.ward@company.com",
      contact: "+1-555-0131",
      office: "Office A",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    },
    {
      id: 32,
      name: "Ella Hughes",
      bio: "Skilled in employee retention strategies.",
      email: "ella.hughes@company.com",
      contact: "+1-555-0132",
      office: "Office B",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1522529599102-1a6c08f8e4a4",
    },
    {
      id: 33,
      name: "Jack Morgan",
      bio: "Expert in team scalability.",
      email: "jack.morgan@company.com",
      contact: "+1-555-0133",
      office: "Office C",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    },
    {
      id: 34,
      name: "Lily Price",
      bio: "Focuses on workplace culture.",
      email: "lily.price@company.com",
      contact: "+1-555-0134",
      office: "Office D",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
    {
      id: 35,
      name: "Owen Bailey",
      bio: "Specializes in performance analytics.",
      email: "owen.bailey@company.com",
      contact: "+1-555-0135",
      office: "Office E",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    {
      id: 36,
      name: "Zoe Foster",
      bio: "Dedicated to leadership training.",
      email: "zoe.foster@company.com",
      contact: "+1-555-0136",
      office: "Office A",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1487412723647-8dcaf443e851",
    },
    {
      id: 37,
      name: "Caleb Stone",
      bio: "Experienced in change management.",
      email: "caleb.stone@company.com",
      contact: "+1-555-0137",
      office: "Office B",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    },
    {
      id: 38,
      name: "Scarlett Long",
      bio: "Skilled in team alignment.",
      email: "scarlett.long@company.com",
      contact: "+1-555-0138",
      office: "Office C",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    },
    {
      id: 39,
      name: "Elijah Cole",
      bio: "Expert in workflow optimization.",
      email: "elijah.cole@company.com",
      contact: "+1-555-0139",
      office: "Office D",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1504257432389-52343af06ae3",
    },
    {
      id: 40,
      name: "Aria Hayes",
      bio: "Focuses on collaborative leadership.",
      email: "aria.hayes@company.com",
      contact: "+1-555-0140",
      office: "Office E",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1517841902196-6c0ebfcdd114",
    },
    {
      id: 41,
      name: "Gabriel Ford",
      bio: "Strong background in team strategy.",
      email: "gabriel.ford@company.com",
      contact: "+1-555-0141",
      office: "Office A",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    },
    {
      id: 42,
      name: "Lila Bryant",
      bio: "Passionate about mentorship programs.",
      email: "lila.bryant@company.com",
      contact: "+1-555-0142",
      office: "Office B",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1522529599102-1a6c08f8e4a4",
    },
    {
      id: 43,
      name: "Samuel Hart",
      bio: "Expert in operational planning.",
      email: "samuel.hart@company.com",
      contact: "+1-555-0143",
      office: "Office C",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    },
    {
      id: 44,
      name: "Violet Dunn",
      bio: "Skilled in team motivation.",
      email: "violet.dunn@company.com",
      contact: "+1-555-0144",
      office: "Office D",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
    {
      id: 45,
      name: "Isaac Wells",
      bio: "Specializes in leadership development.",
      email: "isaac.wells@company.com",
      contact: "+1-555-0145",
      office: "Office E",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    {
      id: 46,
      name: "Ruby Fox",
      bio: "Focuses on employee wellness.",
      email: "ruby.fox@company.com",
      contact: "+1-555-0146",
      office: "Office A",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1487412723647-8dcaf443e851",
    },
    {
      id: 47,
      name: "Julian Lane",
      bio: "Experienced in project oversight.",
      email: "julian.lane@company.com",
      contact: "+1-555-0147",
      office: "Office B",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    },
    {
      id: 48,
      name: "Stella Kim",
      bio: "Skilled in fostering innovation.",
      email: "stella.kim@company.com",
      contact: "+1-555-0148",
      office: "Office C",
      position: "Team Lead",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    },
    {
      id: 49,
      name: "Miles Grant",
      bio: "Expert in team restructuring.",
      email: "miles.grant@company.com",
      contact: "+1-555-0149",
      office: "Office D",
      position: "Senior Manager",
      image: "https://images.unsplash.com/photo-1504257432389-52343af06ae3",
    },
]
const Managers = () => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-6">
      {managers.map((manager) => (
        <Card key={manager.id} className="flex flex-col items-center">
          <CardHeader className="text-center">
            <CardTitle>{manager.name}</CardTitle>
            <CardDescription>{manager.position}</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col items-center text-center">
            <img
              src={manager.image}
              alt={manager.name}
              className="w-32 h-32 rounded-full mb-4 object-cover"
            />
            <p className="mb-2">{manager.bio}</p>
            <p className="text-sm text-gray-600">Email: {manager.email}</p>
            <p className="text-sm text-gray-600">Contact: {manager.contact}</p>
            <p className="text-sm text-gray-600">Office: {manager.office}</p>
          </CardContent>
          <CardFooter className="flex justify-center">
            <Button
              variant="outline"
              className=""
              onClick={() => toast ("MESSAGE SENT SUCESSFULLY .")}
            >
              Send Message
            </Button>
          </CardFooter>
        </Card>
      ))}
    </div>
  );
};

export default Managers;